import unittest

import ecs


class A(ecs.Component):
    pass

class B(ecs.Component):
    pass

class C(ecs.Component):
    pass


class Test_World(unittest.TestCase):

    def test_entity_fill(self):
        world = ecs.World()
        self.assertTrue(world.is_empty())
        a = world.new_entity()
        self.assertFalse(world.has_entity(a))
        world.add_entity(a)
        self.assertTrue(world.is_status("add_entity", "OK"))
        self.assertFalse(world.is_empty())
        self.assertTrue(world.has_entity(a))
        world.add_entity(a)
        self.assertTrue(world.is_status("add_entity", "ALREADY_EXISTS"))
        b = world.new_entity()
        world.add_entity(b)
        self.assertTrue(world.is_status("add_entity", "OK"))
        self.assertFalse(world.is_empty())
        self.assertTrue(world.has_entity(a))
        self.assertTrue(world.has_entity(b))

    def test_component_fill(self):
        world = ecs.World()
        a = world.new_entity()
        world.add_entity(a)
        b = world.new_entity()
        world.add_entity(b)
        self.assertFalse(world.has_component(a, A))
        self.assertTrue(world.is_status("has_component", "OK"))
        world.add_component(a, A())
        self.assertTrue(world.has_component(a, A))
        self.assertTrue(world.is_status("has_component", "OK"))
        world.add_component(b, B())
        self.assertTrue(world.has_component(a, A))
        self.assertFalse(world.has_component(a, B))
        self.assertFalse(world.has_component(b, A))
        self.assertTrue(world.has_component(b, B))
        world.add_component(a, B())
        self.assertTrue(world.has_component(a, A))
        self.assertTrue(world.has_component(a, B))
        self.assertFalse(world.has_component(a, C))
        self.assertFalse(world.has_component(b, A))
        self.assertTrue(world.has_component(b, B))
        self.assertFalse(world.has_component(b, C))
        c = world.new_entity()
        self.assertFalse(world.has_component(c, A))
        self.assertTrue(world.is_status("has_component", "NO_ENTITY"))
        world.add_component(c, A())
        self.assertTrue(world.is_status("add_component", "NO_ENTITY"))
        world.add_component(a, A())
        self.assertTrue(world.is_status("add_component", "ALREADY_EXISTS"))

    def test_get_component(self):
        world = ecs.World()
        a = world.new_entity()
        world.add_entity(a)
        b = world.new_entity()
        world.add_entity(b)
        aa = A()
        world.add_component(a, aa)
        ab = B()
        world.add_component(a, ab)
        bb = B()
        world.add_component(b, bb)
        t = world.get_component(a, A)
        self.assertTrue(world.is_status("get_component", "OK"))
        self.assertIs(t, aa)
        t = world.get_component(a, B)
        self.assertTrue(world.is_status("get_component", "OK"))
        self.assertIs(t, ab)
        t = world.get_component(b, B)
        self.assertTrue(world.is_status("get_component", "OK"))
        self.assertIs(t, bb)
        t = world.get_component(a, C)
        self.assertTrue(world.is_status("get_component", "NO_COMPONENT"))
        c = world.new_entity()
        t = world.get_component(c, C)
        self.assertTrue(world.is_status("get_component", "NO_ENTITY"))

    def test_remove_entity(self):
        world = ecs.World()
        a = world.new_entity()
        world.add_entity(a)
        b = world.new_entity()
        world.add_entity(b)
        self.assertTrue(world.has_entity(a))
        self.assertTrue(world.has_entity(b))
        world.remove_entity(a)
        self.assertTrue(world.is_status("remove_entity", "OK"))
        self.assertFalse(world.has_entity(a))
        self.assertTrue(world.has_entity(b))
        c = world.new_entity()
        world.remove_entity(c)
        self.assertTrue(world.is_status("remove_entity", "NO_ENTITY"))

    def test_remove_component(self):
        world = ecs.World()
        a = world.new_entity()
        world.add_entity(a)
        b = world.new_entity()
        world.add_entity(b)
        world.add_component(a, A())
        world.add_component(a, B())
        world.add_component(b, A())
        world.add_component(b, B())
        self.assertTrue(world.has_component(a, A))
        self.assertTrue(world.has_component(a, B))
        self.assertTrue(world.has_component(b, A))
        self.assertTrue(world.has_component(b, B))
        world.remove_component(a, A)
        self.assertTrue(world.is_status("remove_component", "OK"))
        self.assertFalse(world.has_component(a, A))
        self.assertTrue(world.has_component(a, B))
        self.assertTrue(world.has_component(b, A))
        self.assertTrue(world.has_component(b, B))
        world.remove_component(a, C)
        self.assertTrue(world.is_status("remove_component", "NO_COMPONENT"))
        c = world.new_entity()
        world.remove_component(c, C)
        self.assertTrue(world.is_status("remove_component", "NO_ENTITY"))


class Test_ExtendableEntitySet(unittest.TestCase):

    def test_fill_empty(self):
        world = ecs.World()
        a = world.new_entity()
        world.add_entity(a)
        b = world.new_entity()
        world.add_entity(b)
        c = world.new_entity()
        world.add_entity(c)
        s = ecs.ExtendableEntitySet()
        self.assertTrue(s.is_empty())
        s.get_entity()
        self.assertTrue(s.is_status("get_entity", "EMPTY"))
        s.add_entity(a)
        self.assertTrue(s.is_status("add_entity", "OK"))
        self.assertFalse(s.is_empty())
        e = s.get_entity()
        self.assertTrue(s.is_status("get_entity", "OK"))
        self.assertIs(e, a)
        s.add_entity(b)
        self.assertTrue(s.is_status("add_entity", "OK"))
        e = s.get_entity()
        self.assertIn(e, {a, b})
        s.add_entity(c)
        self.assertTrue(s.is_status("add_entity", "OK"))
        e = s.get_entity()
        self.assertIn(e, {a, b, c})
        s.add_entity(a)
        self.assertTrue(s.is_status("add_entity", "ALREADY_EXISTS"))

        x = s.get_entity()
        self.assertTrue(s.is_status("get_entity", "OK"))
        s.remove_entity(x)
        self.assertTrue(s.is_status("remove_entity", "OK"))
        y = s.get_entity()
        self.assertTrue(s.is_status("get_entity", "OK"))
        s.remove_entity(y)
        self.assertTrue(s.is_status("remove_entity", "OK"))
        z = s.get_entity()
        self.assertTrue(s.is_status("get_entity", "OK"))
        s.remove_entity(z)
        self.assertTrue(s.is_status("remove_entity", "OK"))
        self.assertTrue(s.is_empty())
        self.assertEqual({x, y, z}, {a, b, c})


if __name__ == '__main__':
    unittest.main()
